server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: USERS-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-mongo
      host: localhost
      database: user-mongo
      repositories:
        enabled: true

