server:
  port: 8083
  servlet:
    context-path: /tries
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: TRY-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/try-db
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
token:
  secret: 645367566B5970337336763979244226452948404D6351655468576D5A713474


authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer